function CreateClockApp(){this.construct();this.dragHandler=new DragHandler(this.windowWrapper);this.zIndexHandler=new ZIndexHandler(this.windowWrapper)}
CreateClockApp.prototype.construct=function(){this.windowWrapper=CreateDiceApp.prototype.createElement("div",{className:"clock-window-wrapper",appendTo:document.getElementById("page-content-wrapper")});this.menuWrapper=CreateDiceApp.prototype.createElement("div",{className:"clock-menubar-wrapper",appendTo:this.windowWrapper});this.closeBtn=CreateDiceApp.prototype.createElement("div",{className:"close",appendTo:this.menuWrapper,event:{click:function(){CreateDiceApp.prototype.deStruct.call(this)}.bind(this)}});
this.contentWrapper=CreateDiceApp.prototype.createElement("div",{className:"clock-content-wrapper",appendTo:this.windowWrapper});this.clockDigitWrapperHour=CreateDiceApp.prototype.createElement("ul",{className:["clock-digit-wrapper","hour"],appendTo:this.contentWrapper});for(var a=0;2>a;a++)this.hourLi=CreateDiceApp.prototype.createElement("li",{className:"clock-digit-zero",appendTo:this.clockDigitWrapperHour});this.clockDigitWrapperMinute=CreateDiceApp.prototype.createElement("ul",{className:["clock-digit-wrapper",
"minute"],appendTo:this.contentWrapper});for(a=0;2>a;a++)this.minuteLi=CreateDiceApp.prototype.createElement("li",{className:"clock-digit-zero",appendTo:this.clockDigitWrapperMinute});this.clockDigitWrapperSecond=CreateDiceApp.prototype.createElement("ul",{className:["clock-digit-wrapper","second"],appendTo:this.contentWrapper});for(a=0;2>a;a++)this.secondLi=CreateDiceApp.prototype.createElement("li",{className:"clock-digit-zero",appendTo:this.clockDigitWrapperSecond})};function CreateDiceApp(){this.construct();this.sum=0;this.die=[];this.sound=new Audio("src/wav/add.wav");this.sound.preload="auto";this.dragHandler=new DragHandler(this.windowWrapper);this.zIndexHandler=new ZIndexHandler(this.windowWrapper)}
CreateDiceApp.prototype.construct=function(){this.windowWrapper=this.createElement("div",{className:"dice-window-wrapper",appendTo:document.getElementById("page-content-wrapper")});this.menuWrapper=this.createElement("div",{className:"dice-menubar-wrapper",appendTo:this.windowWrapper});this.closeBtn=this.createElement("div",{className:"close",appendTo:this.menuWrapper,event:{click:function(){this.deStruct()}.bind(this)}});this.toolBarWrapper=this.createElement("div",{className:"dice-toolbar-wrapper",
appendTo:this.windowWrapper});this.toolBarUl=this.createElement("ul",{appendTo:this.toolBarWrapper});this.addDiceBtn=this.createElement("li",{className:"add",appendTo:this.toolBarUl,event:{click:function(){this.addDice();this.calcSum();this.displaySum();this.playSound()}.bind(this)}});this.removeDiceBtn=this.createElement("li",{className:"remove",appendTo:this.toolBarUl,event:{click:function(){this.removeDice();this.calcSum();this.displaySum();this.playSound()}.bind(this)}});this.rollDiceBtn=this.createElement("li",
{className:"roll",appendTo:this.toolBarUl,event:{click:function(){this.rollDice();this.calcSum();this.displaySum();this.playSound()}.bind(this)}});this.liForToolbar=this.createElement("li",{appendTo:this.toolBarUl});this.toolbarInnerUl=this.createElement("ul",{className:"dice-toolbar-counter-wrapper",appendTo:this.liForToolbar});for(var a=0;5>a;a++)this.liZero=this.createElement("li",{className:"zero",appendTo:this.toolbarInnerUl});this.diceContentWrapper=this.createElement("div",{className:"dice-content-wrapper",
appendTo:this.windowWrapper});this.diceWrapperUl=this.createElement("ul",{appendTo:this.diceContentWrapper})};CreateDiceApp.prototype.deStruct=function(){this.windowWrapper&&this.windowWrapper.parentNode.removeChild(this.windowWrapper);this.dragHandler&&this.dragHandler.deStruct();this.zIndexHandler&&this.zIndexHandler.deStruct()};
CreateDiceApp.prototype.createElement=function(a,b){a=document.createElement(a);b.className&&a.classList.add(b.className);if("object"===typeof b.className)for(var c=0;c<b.className.length;c++)a.classList.add(b.className[c]);b.appendTo&&b.appendTo.appendChild(a);if(b.event)for(var d in b.event)a.addEventListener(d,b.event[d]);return a};
CreateDiceApp.prototype.addDice=function(){if(0<this.die.length)var a=Math.floor(this.diceContentWrapper.offsetWidth/(this.die[0].liDice.offsetWidth+8))*Math.floor(this.diceContentWrapper.offsetHeight/(this.die[0].liDice.offsetHeight+8));this.die.length>=a||this.dice()};CreateDiceApp.prototype.dice=function(){var a=new Dice;this.diceWrapperUl.appendChild(a.render());this.die.push(a)};
CreateDiceApp.prototype.removeDice=function(){this.diceWrapperUl.lastChild&&(this.diceWrapperUl.removeChild(this.diceWrapperUl.lastChild),this.die.pop())};CreateDiceApp.prototype.rollDice=function(){for(var a=this.diceWrapperUl.children,b=0;b<a.length;b++){var c=new Dice,d=c.render();this.diceWrapperUl.replaceChild(d,a[b]);this.die[b]=c}};CreateDiceApp.prototype.calcSum=function(){for(var a=this.sum=0;a<this.die.length;a++)this.sum+=this.die[a].value;return this.sum};
CreateDiceApp.prototype.padStartManual=function(a,b,c){a=String(a);c=String("undefined"!==typeof c?c:"");if(a.length>=b)return a;for(b-=a.length;c.length<b;)c+=c;return c.slice(0,b)+a};
CreateDiceApp.prototype.displaySum=function(){var a="zero one two three four five six seven eight nine".split(" ");this.liElems=this.windowWrapper.querySelectorAll(".zero");this.sum=this.calcSum();for(var b=this.padStartManual(this.sum,this.liElems.length,"0"),c=0;c<this.liElems.length;c++){var d=parseInt(b[c]);this.liElems[c].className="";this.liElems[c].classList.add("zero");this.liElems[c].classList.add(a[d])}};CreateDiceApp.prototype.playSound=function(){this.sound.play()};function Dice(){this.construct()}Dice.prototype.construct=function(){this.value=this.roll()};Dice.prototype.roll=function(){return Math.floor(6*Math.random())+1};Dice.prototype.render=function(){this.liDice=document.createElement("li");this.liDice.classList.add("dice","dice-side-"+"one two three four five six".split(" ")[this.value-1]);return this.liDice};(function(){function a(){this.init()}a.prototype.init=function(){document.getElementById("icon-dice").addEventListener("click",this.createDiceApp.bind(this));document.getElementById("icon-clock").addEventListener("click",this.createClockApp.bind(this))};a.prototype.createDiceApp=function(){new CreateDiceApp};a.prototype.createClockApp=function(){new CreateClockApp};document.addEventListener("DOMContentLoaded",function(){new a})})();function DragHandler(a){this.element=a;this.menuBar=this.element.firstChild;this.dragStart=this.dragStart.bind(this);this.onMouseMove=this.onMouseMove.bind(this);this.onMouseUp=this.onMouseUp.bind(this);this.construct()}DragHandler.prototype.construct=function(){this.element.firstChild.addEventListener("mousedown",this.dragStart)};
DragHandler.prototype.dragStart=function(a){a.preventDefault();var b=this.element.getBoundingClientRect();this.offsetX=a.clientX-b.left;this.offsetY=a.clientY-b.top;document.addEventListener("mousemove",this.onMouseMove);document.addEventListener("mouseup",this.onMouseUp)};DragHandler.prototype.onMouseMove=function(a){a.preventDefault();var b=a.clientX-this.offsetX;a=a.clientY-this.offsetY;this.element.style.position="absolute";this.element.style.left=b+"px";this.element.style.top=a+"px"};
DragHandler.prototype.onMouseUp=function(){document.removeEventListener("mousemove",this.onMouseMove);document.removeEventListener("mouseup",this.onMouseUp)};DragHandler.prototype.deStruct=function(){this.element.removeEventListener("mousedown",this.dragStart);document.removeEventListener("mousemove",this.onMouseMove);document.removeEventListener("mouseup",this.onMouseUp)};function ZIndexHandler(a){this.element=a;this.container=this.element.parentElement;this._onMouseDown=this._updateZIndex.bind(this);this.construct()}ZIndexHandler.prototype.construct=function(){this.element.addEventListener("mousedown",this._onMouseDown)};ZIndexHandler.prototype._updateZIndex=function(){this.element.style.zIndex=String(this.getHighestZIndex()+1)};
ZIndexHandler.prototype.getHighestZIndex=function(){for(var a=this.container.children,b=0,c=0;c<a.length;c++){var d=parseInt(window.getComputedStyle(a[c]).zIndex,10)||0;d>b&&(b=d)}return b};ZIndexHandler.prototype.deStruct=function(){this.element.removeEventListener("mousedown",this._onMouseDown)};
