void 0 == window.com && (window.com = {}); void 0 == window.com.vectorpanic && (window.com.vectorpanic = {}); void 0 == window.com.vectorpanic.jsoop && (window.com.vectorpanic.jsoop = {}); com.vectorpanic.jsoop = function () { return { version: "1.2", console: {}, dom: {}, scope: {}, system: {} } }(); com.vectorpanic.jsoop.dom.Element = function (a) { this.element = document.createElement(a || "div"); this.element.parent = this; this.m_emr = this.m_ema = null; this.m_init() }; com.vectorpanic.jsoop.dom.Element.prototype.m_init = function () { this.m_initElement() }; com.vectorpanic.jsoop.dom.Element.prototype.m_initElement = function () { };
com.vectorpanic.jsoop.dom.Element.prototype.bind = function (a, b, c, d) { null == this.m_ema && ("function" === typeof window.addEventListener ? this.m_ema = this.addEventListener : "function" === typeof window.attachEvent && (this.m_ema = this.attachEvent)); return this.m_ema(a, b, c, d) };
com.vectorpanic.jsoop.dom.Element.prototype.unbind = function (a, b, c) { null == this.m_emr && ("function" === typeof window.removeEventListener ? this.m_emr = this.removeEventListener : "function" === typeof window.detachEvent && (this.m_ema = this.detachEvent)); return this.m_emr(a, b, c) }; com.vectorpanic.jsoop.dom.Element.prototype.addEventListener = function (a, b, c, d) { d = d || this; c = null; "function" === typeof this.element.addEventListener && this.element.addEventListener(a, c = function (e) { b.call(d, e) }); return c };
com.vectorpanic.jsoop.dom.Element.prototype.removeEventListener = function (a, b, c) { "function" === typeof this.element.removeEventListener && this.element.removeEventListener(a, b, c || !1) }; com.vectorpanic.jsoop.dom.Element.prototype.attachEvent = function (a, b, c) { c = c || this; var d = null; "function" === typeof this.element.attachEvent && this.element.addEventListener("on" + a, d = function (e) { b.caller(c, window.event) }); return d };
com.vectorpanic.jsoop.dom.Element.prototype.detachEvent = function (a, b) { "function" === typeof this.element.detachEvent && this.element.detachEvent("on" + a, b) }; com.vectorpanic.jsoop.dom.Element.prototype.appendTo = function (a) { a.appendChild(this.element) }; com.vectorpanic.jsoop.dom.Element.prototype.remove = function () { null != this.element.parentNode && this.element.parentNode.removeChild(this.element) }; com.vectorpanic.jsoop.console.Message = function (a, b) { this.id = 0; this.color = a || "#FFFFFF"; this.prefix = b || ""; this.m_title = this.m_text = ""; com.vectorpanic.jsoop.dom.Element.call(this, "li") }; com.vectorpanic.jsoop.console.Message.prototype = new com.vectorpanic.jsoop.dom.Element; com.vectorpanic.jsoop.console.Message.prototype.constructor = com.vectorpanic.jsoop.console.Message;
Object.defineProperty(com.vectorpanic.jsoop.console.Message.prototype, "text", { get: function () { return this.m_text }, set: function (a) { this.m_text = a; this.m_updateInnerHTML() } }); Object.defineProperty(com.vectorpanic.jsoop.console.Message.prototype, "title", { get: function () { return this.m_title }, set: function (a) { this.m_title = a; this.m_updateInnerHTML() } }); com.vectorpanic.jsoop.console.Message.prototype.m_initElement = function () { this.element.style.margin = "0 0 5px 0"; this.element.style.color = this.color };
com.vectorpanic.jsoop.console.Message.prototype.m_updateInnerHTML = function () { this.element.innerHTML = this.prefix.toUpperCase() + " " + this.m_text; this.element.title = this.m_title }; com.vectorpanic.jsoop.console.Notice = function (a, b) { com.vectorpanic.jsoop.console.Message.call(this, "#A0D468", "<i>notice:</i>"); this.id = 0; this.text = a || ""; this.title = b || this.text }; com.vectorpanic.jsoop.console.Notice.prototype = new com.vectorpanic.jsoop.console.Message; com.vectorpanic.jsoop.console.Notice.prototype.constructor = com.vectorpanic.jsoop.console.Notice; com.vectorpanic.jsoop.console.Warning = function (a, b) { com.vectorpanic.jsoop.console.Message.call(this, "#FFCE54", "<i>warning:</i>"); this.id = 1; this.text = a || ""; this.title = b || this.text }; com.vectorpanic.jsoop.console.Warning.prototype = new com.vectorpanic.jsoop.console.Message; com.vectorpanic.jsoop.console.Warning.prototype.constructor = com.vectorpanic.jsoop.console.Warning; com.vectorpanic.jsoop.console.Error = function (a, b) { com.vectorpanic.jsoop.console.Message.call(this, "#FC6E51", "<i>error:</i>"); this.id = 2; this.text = a || ""; this.title = b || this.text }; com.vectorpanic.jsoop.console.Error.prototype = new com.vectorpanic.jsoop.console.Message; com.vectorpanic.jsoop.console.Error.prototype.constructor = com.vectorpanic.jsoop.console.Error; com.vectorpanic.jsoop.console.Critical = function (a, b) { com.vectorpanic.jsoop.console.Message.call(this, "#ED5565", "<i>Critical:</i>"); this.id = 3; this.text = a || ""; this.title = b || this.text }; com.vectorpanic.jsoop.console.Critical.prototype = new com.vectorpanic.jsoop.console.Message; com.vectorpanic.jsoop.console.Critical.prototype.constructor = com.vectorpanic.jsoop.console.Critical; com.vectorpanic.jsoop.console.Messages = function () { this.m_messages = []; com.vectorpanic.jsoop.dom.Element.call(this, "ul") }; com.vectorpanic.jsoop.console.Messages.prototype = new com.vectorpanic.jsoop.dom.Element; com.vectorpanic.jsoop.console.Messages.prototype.constructor = com.vectorpanic.jsoop.console.Messages; Object.defineProperty(com.vectorpanic.jsoop.console.Messages.prototype, "numNotices", { get: function () { for (var a = 0, b = 0; b < this.m_messages.length; b++)0 == this.m_messages[b].id && a++; return a } });
Object.defineProperty(com.vectorpanic.jsoop.console.Messages.prototype, "numWarnings", { get: function () { for (var a = 0, b = 0; b < this.m_messages.length; b++)1 == this.m_messages[b].id && a++; return a } }); Object.defineProperty(com.vectorpanic.jsoop.console.Messages.prototype, "numErrors", { get: function () { for (var a = 0, b = 0; b < this.m_messages.length; b++)2 == this.m_messages[b].id && a++; return a } }); com.vectorpanic.jsoop.console.Messages.prototype.m_initElement = function () { this.element.style.margin = "0px" };
com.vectorpanic.jsoop.console.Messages.prototype.add = function (a, b) { !0 === this.isUnique(a) && (a = 1 === b ? new com.vectorpanic.jsoop.console.Warning(a) : 2 === b ? new com.vectorpanic.jsoop.console.Error(a) : 3 === b ? new com.vectorpanic.jsoop.console.Critical(a) : new com.vectorpanic.jsoop.console.Notice(a), this.m_messages.push(a), a.appendTo(this.element)) }; com.vectorpanic.jsoop.console.Messages.prototype.isUnique = function (a) { for (var b = 0; b < this.m_messages.length; b++)if (a == this.m_messages[b].text) return !1; return !0 }; com.vectorpanic.jsoop.console.Header = function () { this.m_numErrors = this.m_numWarnings = this.m_numNotices = 0; com.vectorpanic.jsoop.dom.Element.call(this, "div") }; com.vectorpanic.jsoop.console.Header.prototype = new com.vectorpanic.jsoop.dom.Element; com.vectorpanic.jsoop.console.Header.prototype.constructor = com.vectorpanic.jsoop.console.Header; Object.defineProperty(com.vectorpanic.jsoop.console.Header.prototype, "notices", { get: function () { return this.m_numNotices }, set: function (a) { this.m_numNotices = a; this.m_updateInnerHTML() } });
Object.defineProperty(com.vectorpanic.jsoop.console.Header.prototype, "warnings", { get: function () { return this.m_numWarnings }, set: function (a) { this.m_numWarnings = a; this.m_updateInnerHTML() } }); Object.defineProperty(com.vectorpanic.jsoop.console.Header.prototype, "errors", { get: function () { return this.m_numErrors }, set: function (a) { this.m_numErrors = a; this.m_updateInnerHTML() } });
com.vectorpanic.jsoop.console.Header.prototype.m_initElement = function () { this.element.style.fontSize = "14px"; this.element.style.padding = "0px"; this.element.style.margin = "0px"; this.element.style.fontWeight = 400; this.element.style.letterSpacing = "1px"; this.element.innerHTML = "JsOOP v" + com.vectorpanic.jsoop.version };
com.vectorpanic.jsoop.console.Header.prototype.m_updateInnerHTML = function () { this.element.innerHTML = "JsOOP v" + com.vectorpanic.jsoop.version + " - Notices: " + this.m_numNotices + ", Warnings: " + this.m_numWarnings + ", Errors: " + this.m_numErrors }; com.vectorpanic.jsoop.console.Console = function () { this.m_messages = this.m_header = null; com.vectorpanic.jsoop.dom.Element.call(this, "div") }; com.vectorpanic.jsoop.console.Console.prototype = new com.vectorpanic.jsoop.dom.Element; com.vectorpanic.jsoop.console.Console.prototype.constructor = com.vectorpanic.jsoop.console.Console;
com.vectorpanic.jsoop.console.Console.prototype.log = function (a, b, c) { void 0 != this.m_messages && this.m_messages.add(a, b); void 0 != this.m_header && (this.m_header.notices = this.m_messages.numNotices); void 0 != this.m_header && (this.m_header.warnings = this.m_messages.numWarnings); void 0 != this.m_header && (this.m_header.errors = this.m_messages.numErrors) }; com.vectorpanic.jsoop.console.Console.prototype.m_init = function () { com.vectorpanic.jsoop.dom.Element.prototype.m_init.call(this); this.m_initHeader(); this.m_initMessages() };
com.vectorpanic.jsoop.console.Console.prototype.m_initElement = function () {
    this.element.style.fontFamily = "Helvetica Neue, Helvetica, Arial, sans-serif"; this.element.style.fontSize = "14px"; this.element.style.fontWeight = "300"; this.element.style.backgroundColor = "#434A54"; this.element.style.position = "absolute"; this.element.style.left = "10px"; this.element.style.top = "10px"; this.element.style.padding = "10px"; this.element.style.margin = "0px"; this.element.style.borderRadius = "5px"; this.element.style.color = "#F5F7FA";
    this.element.style.maxWidth = "640px"; this.element.style.zIndex = "9999"
}; com.vectorpanic.jsoop.console.Console.prototype.m_initHeader = function () { this.m_header = new com.vectorpanic.jsoop.console.Header; this.m_header.appendTo(this.element) }; com.vectorpanic.jsoop.console.Console.prototype.m_initMessages = function () { this.m_messages = new com.vectorpanic.jsoop.console.Messages; this.m_messages.appendTo(this.element) }; com.vectorpanic.jsoop.system.Config = function (a, b, c, d) { this.aliases = b || []; this.exceptions = d || []; this.namespaces = []; this.packages = c || []; this.scope = a || window; this.original = Object.getOwnPropertyNames(this.scope) }; com.vectorpanic.jsoop.system.Validator = function (a, b) {
    this.MESSAGE_UNDEFINED_CLASS = "Class '%C' is imported but its object representation can not be found in the code base, please check that the class exists and is imported correctly."; this.MESSAGE_INLINE_JAVASCRIPT = "Codebase contains script elements that advocate inline code, ie the src attribute is missing."; this.MESSAGE_SCOPE_LEAKAGE = "Property '%P' was found in the global scope and does not relate to any class, assumed to be leakage."; this.MESSAGE_UNDEFINED_PACKAGE =
        "Package '%P' is declared but not defined."; this.MESSAGE_INVALID_PACKAGE = "Package '%P' is of invalid data type, use objects for package structures."; this.m_configs = a || []; this.m_console = b || new com.vectorpanic.jsoop.ui.Console; this.m_classes = []
}; com.vectorpanic.jsoop.system.Validator.prototype.refresh = function () { this.m_checkScriptFiles(); this.m_checkObjectStructure() };
com.vectorpanic.jsoop.system.Validator.prototype.m_checkScriptFiles = function () { for (var a = document.getElementsByTagName("script"), b = 0; b < a.length; b++)a[b].src ? this.m_registerClassFile(a[b].src) : this.m_console.log(this.MESSAGE_INLINE_JAVASCRIPT, 0) };
com.vectorpanic.jsoop.system.Validator.prototype.m_registerClassFile = function (a) { a = a.split("/").pop().split(".")[0]; if (!(-1 < this.m_classes.indexOf(a))) { for (var b = !1, c = 0; c < this.m_configs.length; c++)if (!0 === this.m_isClass(a, this.m_configs[c].scope, this.m_configs[c].packages) || !0 === this.m_isExeption(a)) { b = !0; break } !0 === b ? this.m_classes.push(a) : this.m_console.log(this.MESSAGE_UNDEFINED_CLASS.replace("%C", a), 1) } };
com.vectorpanic.jsoop.system.Validator.prototype.m_isClass = function (a, b, c) { for (var d = 0; d < this.m_configs.length; d++)if (void 0 == c || 0 == c.length) { if ("undefined" !== typeof b[a]) return !0 } else for (var e = 0; e < c.length; e++)if (void 0 != b[c[e]]) if ("[object Object]" == b[c[e]].toString()) { if ("undefined" !== typeof b[c[e]][a]) return !0 } else this.m_console.log(this.MESSAGE_INVALID_PACKAGE.replace("%P", c[e]), 1); else this.m_console.log(this.MESSAGE_UNDEFINED_PACKAGE.replace("%P", c[e]), 1); return !1 };
com.vectorpanic.jsoop.system.Validator.prototype.m_isExeption = function (a) { for (var b = 0; b < this.m_configs.length; b++)if (-1 < this.m_configs[b].exceptions.indexOf(a)) return !0; return !1 };
com.vectorpanic.jsoop.system.Validator.prototype.m_checkObjectStructure = function () { for (var a = 0; a < this.m_configs.length; a++) { var b = Object.getOwnPropertyNames(this.m_configs[a].scope); b = this.m_diff(b, this.m_configs[a].original); b = this.m_diff(b, this.m_classes); b = this.m_diff(b, this.m_getAliases()); for (var c = 0; c < b.length; c++)this.m_console.log(this.MESSAGE_SCOPE_LEAKAGE.replace("%P", b[c]), 2) } };
com.vectorpanic.jsoop.system.Validator.prototype.m_getAliases = function () { for (var a = [], b = 0; b < this.m_configs.length; b++)a.push.apply(a, this.m_configs[b].aliases); return a }; com.vectorpanic.jsoop.system.Validator.prototype.m_diff = function (a, b) { return a.filter(function (c) { return !(-1 < b.indexOf(c)) }) }; com.vectorpanic.jsoop.system.Main = function () {
    function a(g) { k = !0 } function b() { f = new com.vectorpanic.jsoop.console.Console; f.appendTo(document.body); h = new com.vectorpanic.jsoop.system.Validator(e, f); d.add(window.com.vectorpanic.jsoop, ["VPJsOOP", "com"], ["console", "scope", "system"], ["Manifest"]); window.setInterval(c, 2E3); c() } function c() {
        void 0 != h && h.refresh(); !0 === k && void 0 != f && f.log("Program code contains syntax or runtime errors. Validation process has been compromised. Correct the errors and try again.",
            3)
    } var d = {}, e = [new com.vectorpanic.jsoop.system.Config], f = null, h = null, k = !1; d.add = function (g, l, m, n) { g = new com.vectorpanic.jsoop.system.Config(g, l, m, n); e.push(g); c() }; void 0 != window.addEventListener ? window.addEventListener("load", b, "false") : void 0 != window.attachEvent ? window.attachEvent("onload", b) : window.onload = b; void 0 != window.addEventListener ? window.addEventListener("error", a, "false") : void 0 != window.attachEvent ? window.attachEvent("onerror", a) : window.onerror = a; return d
}(); com.vectorpanic.jsoop.scope.Alias = function () { window.VPJsOOP = com.vectorpanic.jsoop.system.Main; return {} }();
